---
- name: Deploy PetClinic
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install Java 1.11
    yum: name=java-1.11.0-openjdk state=present
  - name: Install apache and ensure it has latest version
    yum:
      name: httpd
      state: latest
  - name: Copy jar file
    copy: src=./target/*.jar dest=/opt/
  - name: Execute jar
    shell: java -Dserver.port=8080 -jar opt/*.jar'
  
  
